image:
  repository: ghcr.io/r-droid101/migrate
  tag: latest
  pullPolicy: Always
  pullSecrets: 
    - ghcr-secret

resources: {}

secrets:
  db:
    secretName: db-secret
    usernameKey: username
    passwordKey: password

db:
  host: postgres
  port: 5432
  name: numbersdb
