services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  migrate:
    image: ./migrate
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    restart: "no"
    entrypoint: ["/bin/sh", "-c", "sleep 5 && ./migrate"]


  consumer:
    build: ./consumer
    ports:
      - "9090:9090"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
      - RUNNING_IN_DOCKER=true

  publisher1:
    build: ./publisher
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - db
    environment:
      - PUBLISHER_ID=publisher-1
      - START_NUMBER=1
      - END_NUMBER=10
      - AUTH_TOKEN=${AUTH_TOKEN}

  publisher2:
    build: ./publisher
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - db
    environment:
      - PUBLISHER_ID=publisher-2
      - START_NUMBER=11
      - END_NUMBER=20
      - AUTH_TOKEN=${AUTH_TOKEN}

  publisher3:
    build: ./publisher
    ports:
      - "8083:8080"
    depends_on:
      - redis
      - db
    environment:
      - PUBLISHER_ID=publisher-3
      - START_NUMBER=21
      - END_NUMBER=30
      - AUTH_TOKEN=${AUTH_TOKEN}

  publisher4:
    build: ./publisher
    ports:
      - "8084:8080"
    depends_on:
      - redis
      - db
    environment:
      - PUBLISHER_ID=publisher-4
      - START_NUMBER=31
      - END_NUMBER=40
      - AUTH_TOKEN=${AUTH_TOKEN}

  publisher5:
    build: ./publisher
    ports:
      - "8085:8080"
    depends_on:
      - redis
      - db
    environment:
      - PUBLISHER_ID=publisher-5
      - START_NUMBER=41
      - END_NUMBER=50
      - AUTH_TOKEN=${AUTH_TOKEN}

volumes:
  pgdata:
  redisdata: