image:
  repository: ghcr.io/r-droid101/consumer
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - ghcr-secret

replicaCount: 1

service:
  type: ClusterIP
  port: 9090

secrets:
  db:
    secretName: db-secret
    usernameKey: username
    passwordKey: password
  auth:
    secretName: auth-token
    tokenKey: token

db:
  host: postgres
  port: 5432
  name: numbersdb

redis:
  host: redis:6379
