apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: numbers-system
spec:
  type: {{ .Values.service.type }}
  selector:
    app: consumer
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
