apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
  namespace: numbers-system
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.db.host }}
            - name: DB_PORT
              value: "{{ .Values.db.port }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.db.secretName }}
                  key: {{ .Values.secrets.db.usernameKey }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.db.secretName }}
                  key: {{ .Values.secrets.db.passwordKey }}
            - name: DB_NAME
              value: {{ .Values.db.name }}
      restartPolicy: OnFailure
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
